# Generated by Django 5.0 on 2023-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
